version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" #8000 Ã© do Host
    depends_on:
      - mysql

  mysql:
    container_name: meu_servidor_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: etecjau
      MYSQL_DATABASE: biblioteca
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql #Dentro do docker desktop
      - ./Modelagem/Projeto_Fisico.sql:/docker-entrypoint-initdb.d/Projeto_Fisico.sql:ro

volumes:
  mysql-data: